{% set name = "igwn-cmake-macros" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: f06e11eb87183fce1811d83e8da218f53be0b10ff4682f37aa0ec6b91c47b946

build:
  number: 0

requirements:
  build:
    - cmake
    - make  # [not win]
    - pkg-config
  run_constrained:
    - igwn-cmake <0a0

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --print-errors --exact-version "{{ version }}" igwncmake
    - test -f ${PREFIX}/share/igwn-cmake/cmake/Modules/IGWNCMakeConfig.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\\share\\igwn-cmake\\cmake\\Modules\\IGWNCMakeConfig.cmake exit 1  # [win]

about:
  home: https://git.ligo.org/ldastools/igwn-cmake
  dev_url: https://git.ligo.org/ldastools/igwn-cmake.git
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: This is a collection of CMake functions used as a replacement for autoconf macros
  description: |
    This is a collection of macros and scripts that were developed to aid
    in the process of converting Autotools based projects into CMake.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
